version: "3.8"

networks:
  http-srv:
  frontend:
    external: true

services:
  http-srv:
    image: nginx:alpine
    networks: ['frontend','http-srv']
    container_name: http-srv
    restart: unless-stopped
    volumes:
      - /srv/http/kub:/usr/share/nginx/html/kub:ro
      # Add virtual host for PXE if needed
      # - /srv/pxe/http:/usr/share/nginx/html/pxe:ro
      - /data/compose/http-svc/nginx-default.conf:/etc/nginx/conf.d/default.conf:rw
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.http-srv.rule=Host(`${HTTP_SRV_FQDN}`)"
      - "traefik.http.routers.http-srv.entrypoints=websecure"
      - "traefik.http.routers.http-srv.tls=true"
      - "traefik.http.routers.http-srv.tls.certresolver=route53"
      - "traefik.http.routers.http-srv.service=http-srv-svc"
      - "traefik.http.services.http-srv-svc.loadbalancer.server.port=80"
      # (optional) HSTS
      - "traefik.http.middlewares.hsts.headers.stsseconds=31536000"
      - "traefik.http.routers.http-srv.middlewares=hsts"